{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "luxury-account.fullname" . }}-api
  labels:
    {{- include "luxury-account.api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "luxury-account.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "luxury-account.api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "luxury-account.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-clickhouse
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for ClickHouse to be ready..."
              until nc -z {{ include "luxury-account.fullname" . }}-clickhouse 8123; do
                echo "ClickHouse is unavailable - sleeping"
                sleep 2
              done
              echo "ClickHouse is ready!"
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for RabbitMQ to be ready..."
              until nc -z {{ include "luxury-account.fullname" . }}-rabbitmq 5672; do
                echo "RabbitMQ is unavailable - sleeping"
                sleep 2
              done
              echo "RabbitMQ is ready!"
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          env:
            {{- include "luxury-account.commonEnv" . | nindent 12 }}
            {{- range $key, $value := .Values.api.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: CLICKHOUSE_URL
              value: {{ include "luxury-account.clickhouseUrl" . | quote }}
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: clickhouse-username
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: clickhouse-password
            - name: RABBITMQ_URL
              value: {{ include "luxury-account.rabbitmqUrl" . | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: rabbitmq-password
            - name: MINIO_ENDPOINT
              value: {{ include "luxury-account.minioEndpoint" . | quote }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: minio-secret-key
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: stripe-secret-key
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: stripe-webhook-secret
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: jwt-secret-key
          envFrom:
            - configMapRef:
                name: {{ include "luxury-account.fullname" . }}-api-config
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: app-data
              mountPath: /app/data
      volumes:
        - name: tmp
          emptyDir: {}
        - name: app-data
          emptyDir: {}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 