{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "luxury-account.fullname" . }}-secrets
  labels:
    {{- include "luxury-account.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # ClickHouse credentials
  clickhouse-username: {{ .Values.clickhouse.auth.username | default "luxury_account" | b64enc }}
  clickhouse-password: {{ .Values.clickhouse.auth.password | default (randAlphaNum 32) | b64enc }}
  
  # RabbitMQ credentials
  rabbitmq-username: {{ .Values.rabbitmq.auth.username | default "luxury_account" | b64enc }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | default (randAlphaNum 32) | b64enc }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.auth.erlangCookie | default (randAlphaNum 32) | b64enc }}
  
  # MinIO credentials
  minio-access-key: {{ .Values.minio.auth.rootUser | default "admin" | b64enc }}
  minio-secret-key: {{ .Values.minio.auth.rootPassword | default (randAlphaNum 32) | b64enc }}
  
  # NextAuth secrets
  nextauth-secret: {{ .Values.nextauth.secret | default (randAlphaNum 64) | b64enc }}
  
  # Google OAuth credentials
  google-client-id: {{ .Values.google.clientId | default "" | b64enc }}
  google-client-secret: {{ .Values.google.clientSecret | default "" | b64enc }}
  
  # Stripe credentials
  stripe-publishable-key: {{ .Values.stripe.publishableKey | default "" | b64enc }}  
  stripe-secret-key: {{ .Values.stripe.secretKey | default "" | b64enc }}
  stripe-webhook-secret: {{ .Values.stripe.webhookSecret | default "" | b64enc }}
  stripe-basic-price-id: {{ .Values.stripe.basicPriceId | default "" | b64enc }}
  stripe-pro-price-id: {{ .Values.stripe.proPriceId | default "" | b64enc }}
  stripe-enterprise-price-id: {{ .Values.stripe.enterprisePriceId | default "" | b64enc }}
  
  # JWT secret
  jwt-secret-key: {{ .Values.jwt.secretKey | default (randAlphaNum 64) | b64enc }}
  
  # Monitoring passwords
  {{- if .Values.monitoring.grafana.enabled }}
  grafana-admin-password: {{ .Values.monitoring.grafana.adminPassword | default (randAlphaNum 16) | b64enc }}
  {{- end }}
  
  # Database encryption key
  database-encryption-key: {{ .Values.database.encryptionKey | default (randAlphaNum 64) | b64enc }}
  
  # Session encryption key
  session-encryption-key: {{ .Values.session.encryptionKey | default (randAlphaNum 64) | b64enc }}
{{- end }} 