{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "luxury-account.fullname" . }}-worker
  labels:
    {{- include "luxury-account.worker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "luxury-account.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/worker-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        {{- include "luxury-account.worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "luxury-account.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-services
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for services to be ready..."
              until nc -z {{ include "luxury-account.fullname" . }}-clickhouse 8123 && nc -z {{ include "luxury-account.fullname" . }}-rabbitmq 5672; do
                echo "Services are unavailable - sleeping"
                sleep 5
              done
              echo "All services are ready!"
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command: ["python", "-m", "worker.main"]
          livenessProbe:
            {{- toYaml .Values.worker.livenessProbe | nindent 12 }}
          env:
            {{- include "luxury-account.commonEnv" . | nindent 12 }}
            {{- range $key, $value := .Values.worker.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: CLICKHOUSE_URL
              value: {{ include "luxury-account.clickhouseUrl" . | quote }}
            - name: CLICKHOUSE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: clickhouse-username
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: clickhouse-password
            - name: RABBITMQ_URL
              value: {{ include "luxury-account.rabbitmqUrl" . | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: rabbitmq-password
            - name: MINIO_ENDPOINT
              value: {{ include "luxury-account.minioEndpoint" . | quote }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "luxury-account.fullname" . }}-secrets
                  key: minio-secret-key
          envFrom:
            - configMapRef:
                name: {{ include "luxury-account.fullname" . }}-worker-config
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: worker-data
              mountPath: /app/data
      volumes:
        - name: tmp
          emptyDir: {}
        - name: worker-data
          emptyDir: {}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 